# Generated by Django 5.0.2 on 2024-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
