# Generated by Django 5.0.3 on 2025-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='package_images'),
        ),
    ]
