# Generated by Django 5.0.3 on 2025-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_package_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image1',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_image'),
        ),
    ]
