# Generated by Django 5.0.3 on 2025-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_hotel_hotel_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='travel_way',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10, null=True),
        ),
    ]
