# Generated by Django 5.0.3 on 2025-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
