# Generated by Django 5.0.3 on 2025-03-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_booking_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_deatil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.user_details'),
        ),
    ]
