# Generated by Django 5.0.3 on 2025-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_booking_user_deatil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='U_Aadhar',
            field=models.FileField(blank=True, null=True, upload_to='aadhar/'),
        ),
    ]
