# Generated by Django 5.0.3 on 2025-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_user_details_u_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='U_Aadhar',
            field=models.FileField(null=True, upload_to='aadhar/'),
        ),
    ]
